os:
  - linux
  - osx

language: go
sudo: required

services:
  - docker

go:
  - 1.6
  - 1.5
install:
  - go get -v golang.org/x/exp/ebnf
  - make build
script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - make test
#  - goveralls -coverprofile=coverage.txt -service=travis-ci
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install codecov  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install codecov; fi
after_success:
  codecov
notifications:
  email:
    - tiago.natel@neoway.com.br
